import type { Level } from './types';

export type Difficulty = 'starter' | 'classic' | 'expert';

export interface Pack {
  id: string;
  name: string;
  difficulty: Difficulty;
  levels: Level[];
}

/** Look up a Pack by id (#15); unknown ids fall back to the first Pack. */
export function findPackById(packs: Pack[], packId: string): Pack {
  return packs.find((p) => p.id === packId) ?? packs[0];
}

/** Capitalized Difficulty for display and accessible labels (#15). */
export function displayDifficulty(difficulty: Difficulty): string {
  return difficulty.charAt(0).toUpperCase() + difficulty.slice(1);
}

/**
 * Shared Pack accessible label (#15): one shape for Pack entry buttons,
 * Pack tabs, and tabpanels instead of rebuilding the string per site.
 */
export function packAriaLabel(pack: Pack, done: number, total: number): string {
  return `${pack.name} Pack, ${displayDifficulty(pack.difficulty)} Difficulty, ${done} of ${total} complete`;
}

/**
 * v1 Free Play Pack: 30 Levels ramped 5x5 to 8x8.
 * Generated by scripts/generate-pack.ts (seed 20260922). Do not edit by hand.
 */
export const PACK: Level[] = [
  {
    "size": 5,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 4,
            "col": 1
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 2
          },
          {
            "row": 4,
            "col": 2
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 0,
            "col": 3
          },
          {
            "row": 4,
            "col": 4
          }
        ]
      }
    ]
  },
  {
    "size": 5,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 4
          },
          {
            "row": 1,
            "col": 4
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 2,
            "col": 0
          },
          {
            "row": 2,
            "col": 4
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 3,
            "col": 0
          },
          {
            "row": 4,
            "col": 0
          }
        ]
      }
    ]
  },
  {
    "size": 5,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 1
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 2
          },
          {
            "row": 4,
            "col": 2
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 0,
            "col": 3
          },
          {
            "row": 4,
            "col": 3
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 0,
            "col": 4
          },
          {
            "row": 4,
            "col": 4
          }
        ]
      }
    ]
  },
  {
    "size": 5,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 1,
            "col": 4
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 2,
            "col": 0
          },
          {
            "row": 3,
            "col": 4
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 4,
            "col": 0
          },
          {
            "row": 4,
            "col": 2
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 4,
            "col": 3
          },
          {
            "row": 4,
            "col": 4
          }
        ]
      }
    ]
  },
  {
    "size": 5,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 4,
            "col": 0
          },
          {
            "row": 0,
            "col": 1
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 2
          },
          {
            "row": 1,
            "col": 2
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 2,
            "col": 2
          },
          {
            "row": 4,
            "col": 2
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 4,
            "col": 3
          },
          {
            "row": 0,
            "col": 4
          }
        ]
      }
    ]
  },
  {
    "size": 5,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 4,
            "col": 0
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 1
          },
          {
            "row": 4,
            "col": 1
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 0,
            "col": 2
          },
          {
            "row": 4,
            "col": 2
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 0,
            "col": 3
          },
          {
            "row": 4,
            "col": 3
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 0,
            "col": 4
          },
          {
            "row": 4,
            "col": 4
          }
        ]
      }
    ]
  },
  {
    "size": 5,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 4
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 1,
            "col": 0
          },
          {
            "row": 1,
            "col": 2
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 1,
            "col": 3
          },
          {
            "row": 1,
            "col": 4
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 2,
            "col": 4
          },
          {
            "row": 3,
            "col": 4
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 4,
            "col": 0
          },
          {
            "row": 4,
            "col": 4
          }
        ]
      }
    ]
  },
  {
    "size": 5,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 4,
            "col": 1
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 2
          },
          {
            "row": 1,
            "col": 2
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 2,
            "col": 2
          },
          {
            "row": 4,
            "col": 2
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 0,
            "col": 3
          },
          {
            "row": 4,
            "col": 3
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 0,
            "col": 4
          },
          {
            "row": 4,
            "col": 4
          }
        ]
      }
    ]
  },
  {
    "size": 6,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 1,
            "col": 0
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 2,
            "col": 0
          },
          {
            "row": 3,
            "col": 0
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 4,
            "col": 0
          },
          {
            "row": 4,
            "col": 5
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 5,
            "col": 0
          },
          {
            "row": 5,
            "col": 5
          }
        ]
      }
    ]
  },
  {
    "size": 6,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 5,
            "col": 0
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 5,
            "col": 1
          },
          {
            "row": 5,
            "col": 2
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 0,
            "col": 3
          },
          {
            "row": 5,
            "col": 3
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 0,
            "col": 4
          },
          {
            "row": 5,
            "col": 4
          }
        ]
      }
    ]
  },
  {
    "size": 6,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 5
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 1,
            "col": 0
          },
          {
            "row": 1,
            "col": 5
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 3,
            "col": 0
          },
          {
            "row": 3,
            "col": 5
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 4,
            "col": 0
          },
          {
            "row": 5,
            "col": 0
          }
        ]
      }
    ]
  },
  {
    "size": 6,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 1
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 5,
            "col": 2
          },
          {
            "row": 5,
            "col": 3
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 0,
            "col": 4
          },
          {
            "row": 5,
            "col": 4
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 0,
            "col": 5
          },
          {
            "row": 3,
            "col": 5
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 4,
            "col": 5
          },
          {
            "row": 5,
            "col": 5
          }
        ]
      }
    ]
  },
  {
    "size": 6,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 5,
            "col": 0
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 1
          },
          {
            "row": 5,
            "col": 1
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 0,
            "col": 2
          },
          {
            "row": 5,
            "col": 2
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 0,
            "col": 3
          },
          {
            "row": 0,
            "col": 4
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 0,
            "col": 5
          },
          {
            "row": 5,
            "col": 5
          }
        ]
      }
    ]
  },
  {
    "size": 6,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 5,
            "col": 0
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 2
          },
          {
            "row": 5,
            "col": 2
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 0,
            "col": 3
          },
          {
            "row": 2,
            "col": 3
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 3,
            "col": 3
          },
          {
            "row": 5,
            "col": 3
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 0,
            "col": 4
          },
          {
            "row": 5,
            "col": 4
          }
        ]
      }
    ]
  },
  {
    "size": 6,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 5
          },
          {
            "row": 1,
            "col": 5
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 2,
            "col": 0
          },
          {
            "row": 2,
            "col": 5
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 4,
            "col": 0
          },
          {
            "row": 4,
            "col": 3
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 4,
            "col": 4
          },
          {
            "row": 4,
            "col": 5
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 5,
            "col": 0
          },
          {
            "row": 5,
            "col": 1
          }
        ]
      },
      {
        "id": "O",
        "endpoints": [
          {
            "row": 5,
            "col": 2
          },
          {
            "row": 5,
            "col": 5
          }
        ]
      }
    ]
  },
  {
    "size": 6,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 1
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 2
          },
          {
            "row": 0,
            "col": 5
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 1,
            "col": 5
          },
          {
            "row": 2,
            "col": 5
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 3,
            "col": 0
          },
          {
            "row": 3,
            "col": 3
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 3,
            "col": 4
          },
          {
            "row": 3,
            "col": 5
          }
        ]
      },
      {
        "id": "O",
        "endpoints": [
          {
            "row": 4,
            "col": 0
          },
          {
            "row": 5,
            "col": 0
          }
        ]
      }
    ]
  },
  {
    "size": 7,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 6,
            "col": 0
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 1
          },
          {
            "row": 0,
            "col": 2
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 6,
            "col": 3
          },
          {
            "row": 0,
            "col": 4
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 0,
            "col": 5
          },
          {
            "row": 6,
            "col": 6
          }
        ]
      }
    ]
  },
  {
    "size": 7,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 6,
            "col": 1
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 2
          },
          {
            "row": 6,
            "col": 3
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 6,
            "col": 4
          },
          {
            "row": 0,
            "col": 5
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 0,
            "col": 6
          },
          {
            "row": 3,
            "col": 6
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 4,
            "col": 6
          },
          {
            "row": 6,
            "col": 6
          }
        ]
      }
    ]
  },
  {
    "size": 7,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 1,
            "col": 0
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 2,
            "col": 6
          },
          {
            "row": 3,
            "col": 6
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 4,
            "col": 0
          },
          {
            "row": 4,
            "col": 2
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 4,
            "col": 3
          },
          {
            "row": 4,
            "col": 6
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 5,
            "col": 6
          },
          {
            "row": 6,
            "col": 0
          }
        ]
      }
    ]
  },
  {
    "size": 7,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 1
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 6,
            "col": 2
          },
          {
            "row": 0,
            "col": 3
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 0,
            "col": 4
          },
          {
            "row": 4,
            "col": 4
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 5,
            "col": 4
          },
          {
            "row": 6,
            "col": 4
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 0,
            "col": 5
          },
          {
            "row": 0,
            "col": 6
          }
        ]
      }
    ]
  },
  {
    "size": 7,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 6
          },
          {
            "row": 1,
            "col": 6
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 2,
            "col": 0
          },
          {
            "row": 2,
            "col": 6
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 3,
            "col": 0
          },
          {
            "row": 3,
            "col": 3
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 3,
            "col": 4
          },
          {
            "row": 3,
            "col": 6
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 4,
            "col": 6
          },
          {
            "row": 5,
            "col": 6
          }
        ]
      },
      {
        "id": "O",
        "endpoints": [
          {
            "row": 6,
            "col": 0
          },
          {
            "row": 6,
            "col": 6
          }
        ]
      }
    ]
  },
  {
    "size": 7,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 6
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 1,
            "col": 0
          },
          {
            "row": 1,
            "col": 6
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 2,
            "col": 0
          },
          {
            "row": 2,
            "col": 3
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 2,
            "col": 4
          },
          {
            "row": 2,
            "col": 6
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 3,
            "col": 6
          },
          {
            "row": 4,
            "col": 6
          }
        ]
      },
      {
        "id": "O",
        "endpoints": [
          {
            "row": 5,
            "col": 6
          },
          {
            "row": 6,
            "col": 0
          }
        ]
      }
    ]
  },
  {
    "size": 7,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 1,
            "col": 0
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 2,
            "col": 0
          },
          {
            "row": 3,
            "col": 0
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 4,
            "col": 0
          },
          {
            "row": 4,
            "col": 6
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 5,
            "col": 0
          },
          {
            "row": 5,
            "col": 6
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 6,
            "col": 0
          },
          {
            "row": 6,
            "col": 4
          }
        ]
      },
      {
        "id": "O",
        "endpoints": [
          {
            "row": 6,
            "col": 5
          },
          {
            "row": 6,
            "col": 6
          }
        ]
      }
    ]
  },
  {
    "size": 8,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 7
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 1,
            "col": 0
          },
          {
            "row": 1,
            "col": 7
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 2,
            "col": 7
          },
          {
            "row": 3,
            "col": 7
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 4,
            "col": 7
          },
          {
            "row": 5,
            "col": 7
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 6,
            "col": 0
          },
          {
            "row": 7,
            "col": 0
          }
        ]
      }
    ]
  },
  {
    "size": 8,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 7,
            "col": 0
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 2
          },
          {
            "row": 7,
            "col": 2
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 7,
            "col": 3
          },
          {
            "row": 7,
            "col": 4
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 0,
            "col": 5
          },
          {
            "row": 7,
            "col": 5
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 0,
            "col": 6
          },
          {
            "row": 0,
            "col": 7
          }
        ]
      }
    ]
  },
  {
    "size": 8,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 7
          },
          {
            "row": 1,
            "col": 7
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 2,
            "col": 0
          },
          {
            "row": 2,
            "col": 7
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 3,
            "col": 0
          },
          {
            "row": 4,
            "col": 0
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 5,
            "col": 0
          },
          {
            "row": 5,
            "col": 1
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 5,
            "col": 2
          },
          {
            "row": 5,
            "col": 7
          }
        ]
      },
      {
        "id": "O",
        "endpoints": [
          {
            "row": 6,
            "col": 0
          },
          {
            "row": 7,
            "col": 0
          }
        ]
      }
    ]
  },
  {
    "size": 8,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 2
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 3
          },
          {
            "row": 0,
            "col": 7
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 1,
            "col": 0
          },
          {
            "row": 1,
            "col": 7
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 3,
            "col": 0
          },
          {
            "row": 3,
            "col": 7
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 5,
            "col": 0
          },
          {
            "row": 5,
            "col": 7
          }
        ]
      },
      {
        "id": "O",
        "endpoints": [
          {
            "row": 6,
            "col": 7
          },
          {
            "row": 7,
            "col": 7
          }
        ]
      }
    ]
  },
  {
    "size": 8,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 7
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 2,
            "col": 0
          },
          {
            "row": 2,
            "col": 7
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 3,
            "col": 0
          },
          {
            "row": 3,
            "col": 7
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 4,
            "col": 0
          },
          {
            "row": 4,
            "col": 7
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 5,
            "col": 0
          },
          {
            "row": 5,
            "col": 7
          }
        ]
      },
      {
        "id": "O",
        "endpoints": [
          {
            "row": 7,
            "col": 0
          },
          {
            "row": 7,
            "col": 7
          }
        ]
      }
    ]
  },
  {
    "size": 8,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 7
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 1,
            "col": 7
          },
          {
            "row": 2,
            "col": 7
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 3,
            "col": 0
          },
          {
            "row": 4,
            "col": 0
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 5,
            "col": 0
          },
          {
            "row": 5,
            "col": 7
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 6,
            "col": 0
          },
          {
            "row": 6,
            "col": 7
          }
        ]
      },
      {
        "id": "O",
        "endpoints": [
          {
            "row": 7,
            "col": 0
          },
          {
            "row": 7,
            "col": 1
          }
        ]
      },
      {
        "id": "C",
        "endpoints": [
          {
            "row": 7,
            "col": 2
          },
          {
            "row": 7,
            "col": 7
          }
        ]
      }
    ]
  },
  {
    "size": 8,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 7
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 1,
            "col": 0
          },
          {
            "row": 1,
            "col": 7
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 2,
            "col": 0
          },
          {
            "row": 2,
            "col": 7
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 3,
            "col": 0
          },
          {
            "row": 3,
            "col": 4
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 3,
            "col": 5
          },
          {
            "row": 3,
            "col": 7
          }
        ]
      },
      {
        "id": "O",
        "endpoints": [
          {
            "row": 4,
            "col": 0
          },
          {
            "row": 4,
            "col": 7
          }
        ]
      },
      {
        "id": "C",
        "endpoints": [
          {
            "row": 5,
            "col": 0
          },
          {
            "row": 6,
            "col": 0
          }
        ]
      },
      {
        "id": "M",
        "endpoints": [
          {
            "row": 7,
            "col": 0
          },
          {
            "row": 7,
            "col": 7
          }
        ]
      }
    ]
  }
];

/**
 * v2 Multi-Pack store (#12): the legacy flat 30-Level Pack partitioned in
 * order into three named Packs of ten. Starter opens on 5x5 Boards,
 * Classic bridges 6x6 into 7x7, Expert closes on 7x7 into 8x8.
 * Difficulty is a Pack property; Board size and Color count stay the
 * per-Level structural signal. `PACK` above is kept as the flattened
 * legacy view so the v1 flat progress migrates slice-by-slice.
 */
export const PACKS: Pack[] = [
  { id: 'starter', name: 'Starter', difficulty: 'starter', levels: PACK.slice(0, 10) },
  { id: 'classic', name: 'Classic', difficulty: 'classic', levels: PACK.slice(10, 20) },
  { id: 'expert', name: 'Expert', difficulty: 'expert', levels: PACK.slice(20, 30) },
];
