import type { Level } from './types';

/**
 * v1 Free Play Pack: 30 Levels ramped 5x5 to 8x8.
 * Generated by scripts/generate-pack.ts (seed 20260922). Do not edit by hand.
 */
export const PACK: Level[] = [
  {
    "size": 5,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 4,
            "col": 1
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 2
          },
          {
            "row": 4,
            "col": 2
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 0,
            "col": 3
          },
          {
            "row": 4,
            "col": 4
          }
        ]
      }
    ]
  },
  {
    "size": 5,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 4
          },
          {
            "row": 1,
            "col": 4
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 2,
            "col": 0
          },
          {
            "row": 2,
            "col": 4
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 3,
            "col": 0
          },
          {
            "row": 4,
            "col": 0
          }
        ]
      }
    ]
  },
  {
    "size": 5,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 1
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 2
          },
          {
            "row": 4,
            "col": 2
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 0,
            "col": 3
          },
          {
            "row": 4,
            "col": 3
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 0,
            "col": 4
          },
          {
            "row": 4,
            "col": 4
          }
        ]
      }
    ]
  },
  {
    "size": 5,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 1,
            "col": 4
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 2,
            "col": 0
          },
          {
            "row": 3,
            "col": 4
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 4,
            "col": 0
          },
          {
            "row": 4,
            "col": 2
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 4,
            "col": 3
          },
          {
            "row": 4,
            "col": 4
          }
        ]
      }
    ]
  },
  {
    "size": 5,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 4,
            "col": 0
          },
          {
            "row": 0,
            "col": 1
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 2
          },
          {
            "row": 1,
            "col": 2
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 2,
            "col": 2
          },
          {
            "row": 4,
            "col": 2
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 4,
            "col": 3
          },
          {
            "row": 0,
            "col": 4
          }
        ]
      }
    ]
  },
  {
    "size": 5,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 4,
            "col": 0
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 1
          },
          {
            "row": 4,
            "col": 1
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 0,
            "col": 2
          },
          {
            "row": 4,
            "col": 2
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 0,
            "col": 3
          },
          {
            "row": 4,
            "col": 3
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 0,
            "col": 4
          },
          {
            "row": 4,
            "col": 4
          }
        ]
      }
    ]
  },
  {
    "size": 5,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 4
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 1,
            "col": 0
          },
          {
            "row": 1,
            "col": 2
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 1,
            "col": 3
          },
          {
            "row": 1,
            "col": 4
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 2,
            "col": 4
          },
          {
            "row": 3,
            "col": 4
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 4,
            "col": 0
          },
          {
            "row": 4,
            "col": 4
          }
        ]
      }
    ]
  },
  {
    "size": 5,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 4,
            "col": 1
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 2
          },
          {
            "row": 1,
            "col": 2
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 2,
            "col": 2
          },
          {
            "row": 4,
            "col": 2
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 0,
            "col": 3
          },
          {
            "row": 4,
            "col": 3
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 0,
            "col": 4
          },
          {
            "row": 4,
            "col": 4
          }
        ]
      }
    ]
  },
  {
    "size": 6,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 1,
            "col": 0
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 2,
            "col": 0
          },
          {
            "row": 3,
            "col": 0
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 4,
            "col": 0
          },
          {
            "row": 4,
            "col": 5
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 5,
            "col": 0
          },
          {
            "row": 5,
            "col": 5
          }
        ]
      }
    ]
  },
  {
    "size": 6,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 5,
            "col": 0
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 5,
            "col": 1
          },
          {
            "row": 5,
            "col": 2
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 0,
            "col": 3
          },
          {
            "row": 5,
            "col": 3
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 0,
            "col": 4
          },
          {
            "row": 5,
            "col": 4
          }
        ]
      }
    ]
  },
  {
    "size": 6,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 5
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 1,
            "col": 0
          },
          {
            "row": 1,
            "col": 5
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 3,
            "col": 0
          },
          {
            "row": 3,
            "col": 5
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 4,
            "col": 0
          },
          {
            "row": 5,
            "col": 0
          }
        ]
      }
    ]
  },
  {
    "size": 6,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 1
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 5,
            "col": 2
          },
          {
            "row": 5,
            "col": 3
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 0,
            "col": 4
          },
          {
            "row": 5,
            "col": 4
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 0,
            "col": 5
          },
          {
            "row": 3,
            "col": 5
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 4,
            "col": 5
          },
          {
            "row": 5,
            "col": 5
          }
        ]
      }
    ]
  },
  {
    "size": 6,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 5,
            "col": 0
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 1
          },
          {
            "row": 5,
            "col": 1
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 0,
            "col": 2
          },
          {
            "row": 5,
            "col": 2
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 0,
            "col": 3
          },
          {
            "row": 0,
            "col": 4
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 0,
            "col": 5
          },
          {
            "row": 5,
            "col": 5
          }
        ]
      }
    ]
  },
  {
    "size": 6,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 5,
            "col": 0
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 2
          },
          {
            "row": 5,
            "col": 2
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 0,
            "col": 3
          },
          {
            "row": 2,
            "col": 3
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 3,
            "col": 3
          },
          {
            "row": 5,
            "col": 3
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 0,
            "col": 4
          },
          {
            "row": 5,
            "col": 4
          }
        ]
      }
    ]
  },
  {
    "size": 6,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 5
          },
          {
            "row": 1,
            "col": 5
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 2,
            "col": 0
          },
          {
            "row": 2,
            "col": 5
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 4,
            "col": 0
          },
          {
            "row": 4,
            "col": 3
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 4,
            "col": 4
          },
          {
            "row": 4,
            "col": 5
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 5,
            "col": 0
          },
          {
            "row": 5,
            "col": 1
          }
        ]
      },
      {
        "id": "O",
        "endpoints": [
          {
            "row": 5,
            "col": 2
          },
          {
            "row": 5,
            "col": 5
          }
        ]
      }
    ]
  },
  {
    "size": 6,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 1
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 2
          },
          {
            "row": 0,
            "col": 5
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 1,
            "col": 5
          },
          {
            "row": 2,
            "col": 5
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 3,
            "col": 0
          },
          {
            "row": 3,
            "col": 3
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 3,
            "col": 4
          },
          {
            "row": 3,
            "col": 5
          }
        ]
      },
      {
        "id": "O",
        "endpoints": [
          {
            "row": 4,
            "col": 0
          },
          {
            "row": 5,
            "col": 0
          }
        ]
      }
    ]
  },
  {
    "size": 7,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 6,
            "col": 0
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 1
          },
          {
            "row": 0,
            "col": 2
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 6,
            "col": 3
          },
          {
            "row": 0,
            "col": 4
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 0,
            "col": 5
          },
          {
            "row": 6,
            "col": 6
          }
        ]
      }
    ]
  },
  {
    "size": 7,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 6,
            "col": 1
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 2
          },
          {
            "row": 6,
            "col": 3
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 6,
            "col": 4
          },
          {
            "row": 0,
            "col": 5
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 0,
            "col": 6
          },
          {
            "row": 3,
            "col": 6
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 4,
            "col": 6
          },
          {
            "row": 6,
            "col": 6
          }
        ]
      }
    ]
  },
  {
    "size": 7,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 1,
            "col": 0
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 2,
            "col": 6
          },
          {
            "row": 3,
            "col": 6
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 4,
            "col": 0
          },
          {
            "row": 4,
            "col": 2
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 4,
            "col": 3
          },
          {
            "row": 4,
            "col": 6
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 5,
            "col": 6
          },
          {
            "row": 6,
            "col": 0
          }
        ]
      }
    ]
  },
  {
    "size": 7,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 1
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 6,
            "col": 2
          },
          {
            "row": 0,
            "col": 3
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 0,
            "col": 4
          },
          {
            "row": 4,
            "col": 4
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 5,
            "col": 4
          },
          {
            "row": 6,
            "col": 4
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 0,
            "col": 5
          },
          {
            "row": 0,
            "col": 6
          }
        ]
      }
    ]
  },
  {
    "size": 7,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 6
          },
          {
            "row": 1,
            "col": 6
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 2,
            "col": 0
          },
          {
            "row": 2,
            "col": 6
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 3,
            "col": 0
          },
          {
            "row": 3,
            "col": 3
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 3,
            "col": 4
          },
          {
            "row": 3,
            "col": 6
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 4,
            "col": 6
          },
          {
            "row": 5,
            "col": 6
          }
        ]
      },
      {
        "id": "O",
        "endpoints": [
          {
            "row": 6,
            "col": 0
          },
          {
            "row": 6,
            "col": 6
          }
        ]
      }
    ]
  },
  {
    "size": 7,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 6
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 1,
            "col": 0
          },
          {
            "row": 1,
            "col": 6
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 2,
            "col": 0
          },
          {
            "row": 2,
            "col": 3
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 2,
            "col": 4
          },
          {
            "row": 2,
            "col": 6
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 3,
            "col": 6
          },
          {
            "row": 4,
            "col": 6
          }
        ]
      },
      {
        "id": "O",
        "endpoints": [
          {
            "row": 5,
            "col": 6
          },
          {
            "row": 6,
            "col": 0
          }
        ]
      }
    ]
  },
  {
    "size": 7,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 1,
            "col": 0
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 2,
            "col": 0
          },
          {
            "row": 3,
            "col": 0
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 4,
            "col": 0
          },
          {
            "row": 4,
            "col": 6
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 5,
            "col": 0
          },
          {
            "row": 5,
            "col": 6
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 6,
            "col": 0
          },
          {
            "row": 6,
            "col": 4
          }
        ]
      },
      {
        "id": "O",
        "endpoints": [
          {
            "row": 6,
            "col": 5
          },
          {
            "row": 6,
            "col": 6
          }
        ]
      }
    ]
  },
  {
    "size": 8,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 7
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 1,
            "col": 0
          },
          {
            "row": 1,
            "col": 7
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 2,
            "col": 7
          },
          {
            "row": 3,
            "col": 7
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 4,
            "col": 7
          },
          {
            "row": 5,
            "col": 7
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 6,
            "col": 0
          },
          {
            "row": 7,
            "col": 0
          }
        ]
      }
    ]
  },
  {
    "size": 8,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 7,
            "col": 0
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 2
          },
          {
            "row": 7,
            "col": 2
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 7,
            "col": 3
          },
          {
            "row": 7,
            "col": 4
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 0,
            "col": 5
          },
          {
            "row": 7,
            "col": 5
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 0,
            "col": 6
          },
          {
            "row": 0,
            "col": 7
          }
        ]
      }
    ]
  },
  {
    "size": 8,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 7
          },
          {
            "row": 1,
            "col": 7
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 2,
            "col": 0
          },
          {
            "row": 2,
            "col": 7
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 3,
            "col": 0
          },
          {
            "row": 4,
            "col": 0
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 5,
            "col": 0
          },
          {
            "row": 5,
            "col": 1
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 5,
            "col": 2
          },
          {
            "row": 5,
            "col": 7
          }
        ]
      },
      {
        "id": "O",
        "endpoints": [
          {
            "row": 6,
            "col": 0
          },
          {
            "row": 7,
            "col": 0
          }
        ]
      }
    ]
  },
  {
    "size": 8,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 2
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 0,
            "col": 3
          },
          {
            "row": 0,
            "col": 7
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 1,
            "col": 0
          },
          {
            "row": 1,
            "col": 7
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 3,
            "col": 0
          },
          {
            "row": 3,
            "col": 7
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 5,
            "col": 0
          },
          {
            "row": 5,
            "col": 7
          }
        ]
      },
      {
        "id": "O",
        "endpoints": [
          {
            "row": 6,
            "col": 7
          },
          {
            "row": 7,
            "col": 7
          }
        ]
      }
    ]
  },
  {
    "size": 8,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 7
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 2,
            "col": 0
          },
          {
            "row": 2,
            "col": 7
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 3,
            "col": 0
          },
          {
            "row": 3,
            "col": 7
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 4,
            "col": 0
          },
          {
            "row": 4,
            "col": 7
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 5,
            "col": 0
          },
          {
            "row": 5,
            "col": 7
          }
        ]
      },
      {
        "id": "O",
        "endpoints": [
          {
            "row": 7,
            "col": 0
          },
          {
            "row": 7,
            "col": 7
          }
        ]
      }
    ]
  },
  {
    "size": 8,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 7
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 1,
            "col": 7
          },
          {
            "row": 2,
            "col": 7
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 3,
            "col": 0
          },
          {
            "row": 4,
            "col": 0
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 5,
            "col": 0
          },
          {
            "row": 5,
            "col": 7
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 6,
            "col": 0
          },
          {
            "row": 6,
            "col": 7
          }
        ]
      },
      {
        "id": "O",
        "endpoints": [
          {
            "row": 7,
            "col": 0
          },
          {
            "row": 7,
            "col": 1
          }
        ]
      },
      {
        "id": "C",
        "endpoints": [
          {
            "row": 7,
            "col": 2
          },
          {
            "row": 7,
            "col": 7
          }
        ]
      }
    ]
  },
  {
    "size": 8,
    "colors": [
      {
        "id": "R",
        "endpoints": [
          {
            "row": 0,
            "col": 0
          },
          {
            "row": 0,
            "col": 7
          }
        ]
      },
      {
        "id": "G",
        "endpoints": [
          {
            "row": 1,
            "col": 0
          },
          {
            "row": 1,
            "col": 7
          }
        ]
      },
      {
        "id": "B",
        "endpoints": [
          {
            "row": 2,
            "col": 0
          },
          {
            "row": 2,
            "col": 7
          }
        ]
      },
      {
        "id": "Y",
        "endpoints": [
          {
            "row": 3,
            "col": 0
          },
          {
            "row": 3,
            "col": 4
          }
        ]
      },
      {
        "id": "P",
        "endpoints": [
          {
            "row": 3,
            "col": 5
          },
          {
            "row": 3,
            "col": 7
          }
        ]
      },
      {
        "id": "O",
        "endpoints": [
          {
            "row": 4,
            "col": 0
          },
          {
            "row": 4,
            "col": 7
          }
        ]
      },
      {
        "id": "C",
        "endpoints": [
          {
            "row": 5,
            "col": 0
          },
          {
            "row": 6,
            "col": 0
          }
        ]
      },
      {
        "id": "M",
        "endpoints": [
          {
            "row": 7,
            "col": 0
          },
          {
            "row": 7,
            "col": 7
          }
        ]
      }
    ]
  }
];
