/**
 * Reproducible Pack emitter (ticket #2).
 *
 * Regenerates src/game/pack.ts from the seeded generator:
 *   1. npx tsc scripts/generate-pack.ts src/game/generator.ts src/game/types.ts \
 *        --outDir /tmp/packgen --module commonjs --target es2022 --skipLibCheck
 *   2. node /tmp/packgen/scripts/generate-pack.js
 *   3. npm run generate-pack  (once wired in package.json)
 *
 * Output is deterministic: same PACK_SEED always yields the same file.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { PACK_PLAN, PACK_SEED, generatePack } from '../src/game/generator';
import type { Level } from '../src/game/types';

function main(): void {
  const pack: Level[] = generatePack(PACK_SEED).map((g) => g.level);
  const body = `import type { Level } from './types';

/**
 * v1 Free Play Pack: ${pack.length} Levels ramped ${PACK_PLAN[0][0]}x${PACK_PLAN[0][0]} to ${PACK_PLAN[PACK_PLAN.length - 1][0]}x${PACK_PLAN[PACK_PLAN.length - 1][0]}.
 * Generated by scripts/generate-pack.ts (seed ${PACK_SEED}). Do not edit by hand.
 */
export const PACK: Level[] = ${JSON.stringify(pack, null, 2)};
`;
  const out = process.argv[2] ?? join(process.cwd(), 'src', 'game', 'pack.ts');
  writeFileSync(out, body);
  console.log(`wrote ${pack.length} Levels to ${out}`);
}

main();
