/**
 * Reproducible Pack emitter (ticket #2).
 *
 * Regenerates src/game/pack.ts from the seeded generator:
 *   npm run generate-pack
 *
 * Output is deterministic: same PACK_SEED always yields the same file.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { PACK_PLAN, PACK_SEED, generatePack } from '../src/game/generator';
import type { Level } from '../src/game/types';

function main(): void {
  const pack: Level[] = generatePack(PACK_SEED).map((g) => g.level);
  const body = `import type { Level } from './types';

export type Difficulty = 'starter' | 'classic' | 'expert';

export interface Pack {
  id: string;
  name: string;
  difficulty: Difficulty;
  levels: Level[];
}

/**
 * v1 Free Play Pack: ${pack.length} Levels ramped ${PACK_PLAN[0][0]}x${PACK_PLAN[0][0]} to ${PACK_PLAN[PACK_PLAN.length - 1][0]}x${PACK_PLAN[PACK_PLAN.length - 1][0]}.
 * Generated by scripts/generate-pack.ts (seed ${PACK_SEED}). Do not edit by hand.
 */
export const PACK: Level[] = ${JSON.stringify(pack, null, 2)};

/**
 * v2 Multi-Pack store (#12): the legacy flat 30-Level Pack partitioned in
 * order into three named Packs of ten. Starter opens on 5x5 Boards,
 * Classic bridges 6x6 into 7x7, Expert closes on 7x7 into 8x8.
 * Difficulty is a Pack property; Board size and Color count stay the
 * per-Level structural signal. \`PACK\` above is kept as the flattened
 * legacy view so the v1 flat progress migrates slice-by-slice.
 */
export const PACKS: Pack[] = [
  { id: 'starter', name: 'Starter', difficulty: 'starter', levels: PACK.slice(0, 10) },
  { id: 'classic', name: 'Classic', difficulty: 'classic', levels: PACK.slice(10, 20) },
  { id: 'expert', name: 'Expert', difficulty: 'expert', levels: PACK.slice(20, 30) },
];
`;
  const out = process.argv[2] ?? join(process.cwd(), 'src', 'game', 'pack.ts');
  writeFileSync(out, body);
  console.log(`wrote ${pack.length} Levels to ${out}`);
}

main();
